config/routes.rb
BlueCarbon::Application.routes.draw do
  root :to => 'pages#home'

  match 'admins/me' => 'admins#me'

  devise_for :admins, path_prefix: 'my', controllers: { sessions: 'sessions' }
  resources :admins

  resources :validations
  match '/export/:habitat' => 'validations#export'
  match '/export' => 'validations#export'
  resources :photos, only: :create
  resources :areas do
    resources :mbtiles, only: :show
  end

  scope "(:locale)", :locale => /en|ar/ do
    match 'home' => 'pages#home'
    match 'about' => 'pages#about'
    match 'help' => 'pages#help'
    match "layout" => 'analysis#index'
  end

  match '/:locale' => 'pages#home'
end

app/views/admins/_form.html.erb
<%= simple_form_for(@admin, :defaults => { :input_html => { :class => 'span8' } }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email, :required => true, :autofocus => true %>
    <%= f.input :password, :required => true %>
    <%= f.input :password_confirmation, :required => true %>

    <%= f.association :roles, :as => :check_boxes, :label => false, :label_method => lambda { |role| "#{role.name.humanize.capitalize}<br> <span class='description'>#{role.description}</span>".html_safe }, :input_html => { :class => nil, :disabled => (@admin == current_admin) } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn-primary", :value => 'Save User' %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<div class="page-header">
  <%= link_to admins_path, :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end if can? :manage, Admin %>
  <%= link_to @admin, :class => 'btn btn-primary' do %>
    <i class="icon-info-sign icon-white"></i>
    Show
  <% end %>

  <% if can? :manage, Admin %>
    <%= link_to admin_path(@admin), :method => :delete, :confirm => "Are you sure?", :class => 'btn btn-danger' do %>
      <i class="icon-remove icon-white"></i>
      Delete
    <% end %>
  <% end %>
  <h1>Editing User</h1>
</div>

<%= render 'form' %>

app/views/admins/index.html.erb
<div class="page-header">
  <%= link_to new_admin_path, :class => 'btn btn-primary' do %>
    <i class="icon-plus icon-white"></i>
    New User
  <% end %>
  <h1>Listing users</h1>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Email</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
<% @admins.each do |admin| %>
    <tr>
      <td><%= admin.email %></td>
      <td><%= link_to 'Show', admin %></td>
      <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
      <td><%= link_to 'Delete', admin_path(admin), :method => :delete, :confirm => "Are you sure?" %></td>
    </tr>
<% end %>
  </tbody>
</table>

app/views/admins/new.html.erb
<div class="page-header">
  <%= link_to admins_path, :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end %>
  <h1>New User</h1>
</div>

<%= render 'form' %>

app/views/admins/show.html.erb
<div class="page-header">
  <%= link_to admins_path, :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end if can? :manage, Admin %>
  <%= link_to edit_admin_path(@admin), :class => 'btn btn-primary' do %>
    <i class="icon-pencil icon-white"></i>
    Edit
  <% end %>

  <% if can? :manage, Admin %>
    <%= link_to admin_path(@admin), :method => :delete, :confirm => "Are you sure?", :class => 'btn btn-danger' do %>
      <i class="icon-remove icon-white"></i>
      Delete
    <% end %>
  <% end %>
  <h1>User</h1>
</div>

<dl>
  <dt>Email:</dt>
  <dd><%= @admin.email %></dd>

  <dt>Roles:</dt>
  <dd><%= @admin.roles.any? && @admin.roles.map(&:name).join(', ') || '-' %></dd>
</dl>