config/routes.rb
BlueCarbon::Application.routes.draw do
  root :to => 'pages#home'

  match 'admins/me' => 'admins#me'

  devise_for :admins, path_prefix: 'my', controllers: { sessions: 'sessions' }
  resources :admins

  resources :validations
  match '/export/:habitat' => 'validations#export'
  match '/export' => 'validations#export'
  resources :photos, only: :create
  resources :areas do
    resources :mbtiles, only: :show
  end

  scope "(:locale)", :locale => /en|ar/ do
    match 'home' => 'pages#home'
    match 'about' => 'pages#about'
    match 'help' => 'pages#help'
    match "layout" => 'analysis#index'
  end

  match '/:locale' => 'pages#home'
end

app/models/area.rb
class Area < ActiveRecord::Base
  attr_accessible :title, :coordinates

  has_many :validations, dependent: :destroy
  has_many :mbtiles, dependent: :destroy

  validates :title, presence: true, uniqueness: true
  validates :coordinates, presence: true

  def geo_json
    "{\"type\":\"Polygon\",\"coordinates\":#{coordinates}"
  end

  def json_coordinates
    json_coordinates = JSON.parse(coordinates)
    json_coordinates << json_coordinates.first

    json_coordinates = json_coordinates.to_s.gsub(", ", " ")
    json_coordinates = json_coordinates.gsub("] [", ", ")
    json_coordinates = json_coordinates.gsub(/(\[)|(\])/, "")

    json_coordinates
  end

  before_create do
    Habitat.all.each do |habitat|
      mbtiles << Mbtile.new(habitat: habitat.name)
    end
  end
end

app/controllers/areas_controller.rb
class AreasController < AdminController
  before_filter :authenticate_admin!
  load_and_authorize_resource

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all

    respond_to do |format|
      format.html # index.html.erb
      format.json
    end
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
    @area = Area.find(params[:id])
    @mbtiles = @area.mbtiles.order(:habitat)

    respond_to do |format|
      format.html # show.html.erb
      format.json
    end
  end

  # GET /areas/new
  # GET /areas/new.json
  def new
    @area = Area.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @area }
    end
  end

  # GET /areas/1/edit
  def edit
    @area = Area.find(params[:id])
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(params[:area])

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render json: @area, status: :created, location: @area }
      else
        format.html { render action: "new" }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /areas/1
  # PUT /areas/1.json
  def update
    @area = Area.find(params[:id])

    respond_to do |format|
      if @area.update_attributes(params[:area])
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area = Area.find(params[:id])
    @area.destroy

    respond_to do |format|
      format.html { redirect_to areas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_form.html.erb
<%= simple_form_for(@area, :defaults => { :input_html => { :class => 'span12' } }) do |f| %>

  <%= f.error_notification %>

  <% unless @area.errors['coordinates'].empty? %>
    <div class="alert alert-error">
      A polygon must be drawn on to the map to define an field site.
    </div>
  <% end %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :coordinates, as: :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn-primary" %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<div class="page-header">
  <%= link_to areas_path, :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end %>
  <%= link_to @area, :class => 'btn btn-primary' do %>
    <i class="icon-info-sign icon-white"></i>
    Show
  <% end %>
  <h1>Editing field site</h1>
</div>

<%= render 'form' %>

app/views/areas/index.html.erb
<div class="page-header">
  <% if can? :manage, Area %>
    <%= link_to new_area_path, :class => 'btn btn-primary' do %>
      <i class="icon-plus icon-white"></i>
      New Field Site
    <% end %>
  <% end %>
  <h1>Field Sites</h1>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <% if can? :manage, Area %>
        <th></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
<% @areas.each do |area| %>
    <tr>
      <td><%= link_to area.title, area %></td>
      <% if can? :manage, Area %>
        <td><%= link_to 'Delete', area, confirm: 'Are you sure?', method: :delete %></td>
      <% end %>
    </tr>
<% end %>
  </tbody>
</table>

app/views/areas/new.html.erb
<div class="static">
  <div id="map"></div>

  <div id="sidebar" class="shadow">
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span12">
          <h5>New area</h5>

          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/areas/show.html.erb
<div class="static">
  <%= javascript_tag "window.areaCoordinates = #{@area.coordinates}" %>
  <div id="map"></div>

  <div id="sidebar" class="shadow">
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span12">
          <h5>Field Site</h5>

          <dl>
            <dt>Title:</dt>
            <dd><%= @area.title %></dd>
          </dl>

          <h5>MBTiles</h5>

          <div class="accordion" id="accordion">
            <% @mbtiles.each do |mbtile| %>
              <div class="accordion-group">
                <div class="accordion-heading">
                  <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse_<%= mbtile.habitat %>">
                    <%= mbtile.habitat.humanize %>
                  </a>
                </div>
                <div id="collapse_<%= mbtile.habitat %>" class="accordion-body collapse">
                  <div class="accordion-inner">
                    <dl>
                      <dt>Last generation started at:</dt>
                      <dd><%= mbtile.last_generation_started_at || '-' %></dd>

                      <dt>Last generated at:</dt>
                      <dd><%= mbtile.last_generated_at || '-' %></dd>

                      <dt>Status:</dt>
                      <dd><%= mbtile.status %></dd>
                    </dl>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>