config/routes.rb
BlueCarbon::Application.routes.draw do
  root :to => 'pages#home'

  match 'admins/me' => 'admins#me'

  devise_for :admins, path_prefix: 'my', controllers: { sessions: 'sessions' }
  resources :admins

  resources :validations
  match '/export/:habitat' => 'validations#export'
  match '/export' => 'validations#export'
  resources :photos, only: :create
  resources :areas do
    resources :mbtiles, only: :show
  end

  scope "(:locale)", :locale => /en|ar/ do
    match 'home' => 'pages#home'
    match 'about' => 'pages#about'
    match 'help' => 'pages#help'
    match "layout" => 'analysis#index'
  end

  match '/:locale' => 'pages#home'
end

app/views/layouts/_sign_in.html.erb
<% if admin_signed_in? %>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= truncate("#{current_admin.email}", :length => 22, :omission => '...') %> <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><%= link_to "Admin", validations_path %></li>
      <li><%= link_to "My Account", edit_admin_path(current_admin) %></li>
      <li class="divider"></li>
      <li><%= link_to "Logout", destroy_admin_session_path, method: :delete %></li>
    </ul>
  </li>
<% else %>
  <%= link_to t('sign_in'), new_admin_session_path %>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>BlueCarbon</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <!--[if lte IE 8]>
    <%= stylesheet_link_tag "leaflet.ie.css" %>
    <%= stylesheet_link_tag "leaflet.draw.ie.css" %>
  <![endif]-->
  <%= javascript_include_tag "polyglot" %>
  <script>
    var polyglot = new Polyglot({
      phrases: <%= raw @phrases.to_json %>,
      locale: "<%= I18n.locale %>"
    });
  </script>

  <%= stylesheet_link_tag    "application" %>
  <%= stylesheet_link_tag "pages" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>
<body>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container-fluid">
        <%= link_to "/en#{home_path}", :class => 'homepage-banner' do %>
          <img class="one" src="/assets/header-new.png">
        <% end %>

        <ul class="nav pull-right">
          <%= content_tag(:li, link_to("Validations", validations_path), class: params[:controller] == 'validations' ? 'active' : nil) if can? :read, Validation %>
          <%= content_tag(:li, link_to("Users", admins_path), class: params[:controller] == 'admins' ? 'active' : nil) if can? :manage, Admin %>
          <%= content_tag(:li, link_to("iPad Admin", areas_path), class: params[:controller] == 'areas' ? 'active' : nil) if can? :read, Area %>

          <% if admin_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= truncate("#{current_admin.email}") %> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "My Account", edit_admin_path(current_admin) %></li>
                <li class="divider"></li>
                <li><%= link_to "Logout", destroy_admin_session_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Login', new_admin_session_path %></li>
          <% end %>
        </ul>
        <img class="two" src="/assets/header-2.png">
        <a class="agedi" href="http://www.agedi.ae" target="_blank">AGEDI.ae</a>
      </div>
    </div>
  </div>

  <div class="container">
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %>

    <%= yield %>

    <div id='footer'>
      <%= image_tag 'agedi_logo.png', size: "150x43" %>
    </div>
  </div>

  <%= javascript_include_tag "polyglot" %>
  <script>
    var polyglot = new Polyglot({
      phrases: <%= raw @phrases.to_json %>,
      locale: "<%= I18n.locale %>"
    });
  </script>
	
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-41879061-1', 'unep-wcmc.org');
	  ga('send', 'pageview');

	</script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>BlueCarbon</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <!--[if lte IE 8]>
    <%= stylesheet_link_tag "leaflet.ie.css" %>
    <%= stylesheet_link_tag "leaflet.draw.ie.css" %>
  <![endif]-->

  <link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=PT+Mono' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag "opentip.css" %>
  <%= stylesheet_link_tag "application" %>
  <%= stylesheet_link_tag "pages" %>

  <%= javascript_include_tag "polyglot" %>
  <script>
    var polyglot = new Polyglot({
      phrases: <%= raw @phrases.to_json %>,
      locale: "<%= I18n.locale %>"
    });
  </script>

  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container-fluid">
        <%= link_to home_path, :class => 'homepage-banner' do %>
            <% if I18n.locale == I18n.default_locale %>
            <img class="one" src="/assets/header-new.png">
            <% else %>
            <img class="one" src="/assets/header-new.png">
            <%end%>
        <% end %>

        <ul class="nav pull-right">
          <li><%= link_to t('help'), help_path %></li>
          <li><%= link_to t('about'), about_path %></li>
          <li id="language">
            <% if I18n.locale == I18n.default_locale %>
              <%= link_to "عربي/عربى", :locale=>'ar'%>
            <% else %>
              <%= link_to "ENGLISH", :locale=>'en'%>
            <%end%>
          </li>
        </ul>
        <img class="two" src="/assets/header-2.png">
        <a class="agedi" href="http://www.agedi.ae" target="_blank">AGEDI.ae</a>
      </div>
    </div>
  </div>

  <div class="container">
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %>
    <%= yield %>
  </div>

  <footer class="navbar navbar-fixed-bottom">
    <div class="navbar-inner">
        <div class="links pull-left">
          <%= t('developed_by') %> <br>
          <a href="http://www.agedi.ae">
            <img src="/assets/agedi_group_logo.png" alt="Supporters" class="img-footer-supporters">
          </a>
          <a href="https://www.ead.ae">
            <img src="/assets/eaad_group_logo.png" alt="Supporters" class="img-footer-supporters">
          </a>
          <a href="http://www.grida.no">
            <img src="/assets/arendal_group_logo.png" alt="Supporters" class="img-footer-supporters">
          </a>
          <a href="http://www.unep-wcmc.org">
            <img src="/assets/wcmc_group_logo.png" alt="Supporters" class="img-footer-supporters">
          </a>
        </div>
        <ul class="nav pull-right">
          <li><%= render "layouts/sign_in" %></li>
          <li><a href="mailto:info@agedi.ae" target="_top"><%= t('contact') %></a></li>
        </div>
      </div>
    </div>
  </footer>
  <script>
    // Lovely hack to fix bootstrap on mobile devices
    !function ($) {
      $(function(){
        $('body').on('touchstart.dropdown', '.dropdown-menu', function (e) {
          e.stopPropagation();
        });
        $(document).on('click','.dropdown-menu a',function(){
          document.location = $(this).attr('href');
        });
      })
    }(window.jQuery)
  </script>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

          ga('create', 'UA-41879061-1', 'unep-wcmc.org');
          ga('send', 'pageview');

  </script>
</body>
</html>

app/views/layouts/email.html.erb
<%= yield %>

app/views/layouts/iframe.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>BlueCarbon</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <%= stylesheet_link_tag "opentip.css" %>
  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <!--[if lte IE 8]>
    <%= stylesheet_link_tag "leaflet.ie.css" %>
    <%= stylesheet_link_tag "leaflet.draw.ie.css" %>
  <![endif]-->

  <link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>

  <%= javascript_include_tag "polyglot" %>
  <script>
    var polyglot = new Polyglot({
      phrases: <%= raw @phrases.to_json %>,
      locale: "<%= I18n.locale %>"
    });
  </script>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container iframe">
      <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html <% if I18n.locale == :ar %> dir="rtl" <% end %>>
<head>
  <meta charset="utf-8">
  <title>BlueCarbon</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag "pages" %>
  <%= javascript_include_tag "pages" %>

  <%= csrf_meta_tags %>
</head>
<body class="<%= @background %>">
  <div class="page">
    <header dir="ltr">
      <div class="outer"></div>
      <div class="inner">
        <div id="home" class="banner <%= @active %>">
          <%= link_to home_path, :class => 'homepage-banner' do %>
            <% if I18n.locale == I18n.default_locale %>
            <img class="one" src="/assets/header-new.png">
            <% else %>
            <img class="one" src="/assets/header-new.png">
            <%end%>
          <% end %>
        </div>
        <div class="nav">
          <div id="tool" class="<%= @active %>"><%= link_to t('tool'), layout_path %></div>
          <div id="help" class="<%= @active %>"><%= link_to t('help'), help_path %></div>
          <div id="about" class="<%= @active %>"><%= link_to t('about'), about_path %></div>
          <div id="language" class="<%= @active %>">
            <% if I18n.locale == I18n.default_locale %>
              <%= link_to "عربي/عربى", :locale=>'ar'%>
            <% else %>
              <%= link_to "ENGLISH", :locale=>'en'%>
            <%end%>
          </div>
          <img class="two" src="/assets/header-2.png">
          <a class="agedi" href="http://www.agedi.ae" target="_blank">AGEDI.ae</a>
        </div>
      </div>
    </header>
  <%= yield %>
    <footer dir="ltr">
      <div class="inner">
        <div id="attributions">
          <%= t('developed_by') %> <br>
          <a href="http://www.agedi.ae">
            <img src="/assets/agedi_group_logo.png" alt="Supporters" class="img-footer-supporters">
          </a>
          <a href="https://www.ead.ae">
            <img src="/assets/eaad_group_logo.png" alt="Supporters" class="img-footer-supporters">
          </a>
          <a href="http://www.grida.no">
            <img src="/assets/arendal_group_logo.png" alt="Supporters" class="img-footer-supporters">
          </a>
          <a href="https://www.unep-wcmc.org">
            <img src="https://s3.amazonaws.com/wcmc.logo/UN-Environment-WCMC+logo+2017.svg" alt="Supporters" class="wcmc-logo img-footer-supporters">
          </a>
        </div>
        <div id="authentication" class="navbar"><%= render "layouts/sign_in" %></div>
        <div id="contact"><a href="mailto:info@agedi.ae" target="_top"><%= t('contact') %></a></div>

      </div>
    </footer>
  </div>
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-41879061-1', 'unep-wcmc.org');
	  ga('send', 'pageview');

	</script>
</body>
</html>